feat(APIM-528): add API tests for upload file in deal folder endpoint
UK-Export-Finance/estore-api pull request #138
Opened 2023-07-19 13:53 UTC by oscar-richardson-softwire

## Introduction

When we completed [APIM-138](https://ukef-dtfs.atlassian.net/browse/APIM-138) and added the endpoint to upload files to SharePoint, we didn't include API or unit tests for this functionality.

## Resolution

This PR adds API (but not unit) tests for this functionality.

2023-07-20 15:43 UTC, lmarrai-sw requested changes
Thanks @oscar-richardson-softwire

2023-07-20 15:43 UTC, lmarrai-sw commented on test/deal-folder/post-document-in-deal-folder.api-test.ts
> +    });
We test `buyerName` twice :)

2023-07-20 16:04 UTC, oscar-richardson-softwire commented on test/deal-folder/post-document-in-deal-folder.api-test.ts
> +    });
Good spot, removed :)

2023-07-27 11:42 UTC, lmarrai-sw requested changes

2023-07-27 11:42 UTC, lmarrai-sw commented on src/constants/file-location-path.constant.ts
> +  REGEX: /^[a-fA-F\d]{24}(\/[\w\-:\\()\s]+)*$/,
It looks like we've accidentally changed the `REGEX` here

2023-07-27 14:55 UTC, lmarrai-sw commented on src/constants/file-location-path.constant.ts
> +  REGEX: /^[a-fA-F\d]{24}(\/[\w\-:\\()\s]+)*$/,
The linter uses the [safe-regex](https://www.npmjs.com/package/safe-regex) package which can give false positives as it's a simple (but quick) check. I've put the regex into another checker (https://devina.io/redos-checker, which uses [recheck](https://github.com/makenowjust-labs/recheck)) which says that it's safe. I'll bring this up with the team to see if we want to move to a better but slower regex checker

2023-07-27 14:56 UTC, lmarrai-sw approved these changes

2023-07-28 08:11 UTC, merged